openapi: 3.0.0
info:
  title: Projeto FTT API
  description: API para gerenciar personagens de um programa de TV
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Servidor de desenvolvimento local
paths:
  /characters/:
    post:
      summary: Criar um novo personagem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  description: Nome do personagem
                descricao:
                  type: string
                  description: Descrição do personagem
                link_imagem:
                  type: string
                  description: Link da imagem do personagem
                programa:
                  type: string
                  description: Nome do programa ao qual o personagem pertence
                animador:
                  type: string
                  description: Nome do animador responsável pelo personagem
            required:
              - nome
              - descricao
      responses:
        '201':
          description: Personagem criado com sucesso
        '400':
          description: Erro de validação no formulário
        '500':
          description: Erro interno do servidor ao criar o personagem
    get:
      summary: Obter a lista de personagens
      responses:
        '200':
          description: Lista de personagens obtida com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    nome:
                      type: string
                      description: Nome do personagem
                    descricao:
                      type: string
                      description: Descrição do personagem
                    link_imagem:
                      type: string
                      description: Link da imagem do personagem
                    programa:
                      type: string
                      description: Nome do programa ao qual o personagem pertence
                    animador:
                      type: string
                      description: Nome do animador responsável pelo personagem
        '500':
          description: Erro interno do servidor ao obter a lista de personagens
  /character/{character_id}:
    get:
      summary: Obter detalhes de um personagem específico
      parameters:
        - in: path
          name: character_id
          description: ID do personagem a ser obtido
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Detalhes do personagem obtidos com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                    description: Nome do personagem
                  descricao:
                    type: string
                    description: Descrição do personagem
                  link_imagem:
                    type: string
                    description: Link da imagem do personagem
                  programa:
                    type: string
                    description: Nome do programa ao qual o personagem pertence
                  animador:
                    type: string
                    description: Nome do animador responsável pelo personagem
        '404':
          description: Personagem não encontrado
        '500':
          description: Erro interno do servidor ao obter os detalhes do personagem
